using System.Net.Http.Headers;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using flightmvc.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
namespace flightmvc
{
public class BookingController : Controller
{
    private readonly Ace52024Context db;

    public BookingController(Ace52024Context _db)
    {
        db = _db;
    }

    // GET: Booking
    public static List<BookingIvy> b=new List<BookingIvy>();
        public async Task< ActionResult> BookIndex()
        {
         List<BookingIvy> bookings=new List<BookingIvy>();
            
                HttpClient client= new HttpClient();
                 client.DefaultRequestHeaders.Clear();
                //Define request data format  
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                //Sending request to find web api REST service resource GetAllEmployees using HttpClient  
                HttpResponseMessage Res = await client.GetAsync("http://localhost:5214/api/Booking");

                //Checking the response is successful or not which is sent using HttpClient  
                if (Res.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    var response = Res.Content.ReadAsStringAsync().Result;

                    
                    //Deserializing the response recieved from web api and storing into the Employee list  
                    try{
                    b = JsonConvert.DeserializeObject<List<BookingIvy>>(response);
                    }
                    catch(JsonException ex)
                    {
                        Console.WriteLine(ex.Message);
                    }
                

                }
                //returning the employee list to view  
                return View(b);
    }

    // GET: Booking/Details/5
    public IActionResult Details(int? id)
    {
        if (id == null)
        {
            return RedirectToAction("BookIndex");
        }

        //var booking = db.BookingIvies.SingleOrDefault(x => x.BookingId == id);

       var booking=db.BookingIvies.Include(x=>x.Flight).Include(x=>x.Customer).SingleOrDefault(x=>x.BookingId==id);
        if (booking == null)
        {
            return RedirectToAction("BookIndex");
        }
        ViewBag.AutoGeneratedFlightId=$"{booking.Source}-{booking.Destination}";

        return View(booking);
    }

    //GET: Booking/Create
    public IActionResult Create()
    {
        ViewBag.Sources = new SelectList(db.FlightsIvies.Select(f => f.Source).Distinct().ToList());
        ViewBag.Destinations = new SelectList(db.FlightsIvies.Select(f => f.Destination).Distinct().ToList());

        ViewBag.Customer=new SelectList(db.CustomerIvies.Select(f=>f.CustomerId));
       
       
        return View();
    }

    [HttpPost]
  
    public async Task<IActionResult> Create(BookingIvy booking)
    {
        
        if (ModelState.IsValid)
        {
           
            
                bool validFlight=db.FlightsIvies.Any(x=>x.Source==booking.Source &x.Destination==booking.Destination);

                if(!validFlight)
                {
                    ModelState.AddModelError(string.Empty,"No valid flight exist for the selected source and destination");
                    return View(booking);
                }
                booking.FlightId=GenerateFlightId(booking.Source,booking.Destination);
                booking.TotalCost=TotalCost(booking.FlightId,booking.NoOfPassengers);
                booking.BookingDate=DateTime.Now;
                using(var client =new HttpClient())
                {
                    StringContent content=new StringContent(JsonConvert.SerializeObject(booking),Encoding.UTF8,"application/json");
                    HttpResponseMessage response=await client.PostAsync("http://localhost:5214/api/Booking",content);

                    if(response.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Details",new{id=booking.BookingId}); 
                    }
                }
                
                // db.BookingIvies.Add(booking);
                // await db.SaveChangesAsync();

                
            
        }

      
        ViewBag.Sources = db.FlightsIvies.Select(f => f.Source).Distinct().ToList();
        ViewBag.Destinations = db.FlightsIvies.Select(f => f.Destination).Distinct().ToList();

        return View(booking);
        //return BadRequest(ModelState);
    }

    private int GenerateFlightId(string source ,string destinations)
    {
        int flightId=db.FlightsIvies.Where(x=>x.Source==source && x.Destination==destinations).Select(x=>x.FlightId).SingleOrDefault();
        if(flightId<=0)
        {
            return 0;
        }
        return flightId;
    }

    private decimal TotalCost(int? flightId, int? NoOfPassengers)
    {
        if(!flightId.HasValue|| flightId.Value<=0||!NoOfPassengers.HasValue|| NoOfPassengers.Value<=0)

        {
            return 0.00M;
        }
        decimal? rate=db.FlightsIvies.Where(x=>x.FlightId==flightId).Select(x=>x.Rate).SingleOrDefault();

        if(!rate.HasValue||rate.Value<=0)
        {
            return 0.00M;
        }
        return rate.Value* NoOfPassengers.Value;
    }

    // GET: Booking/Edit/5
    public IActionResult Edit(int? id)
    {
        if (id == null)
        {
            return RedirectToAction("BookIndex");
        }

        var booking = db.BookingIvies.SingleOrDefault(b => b.BookingId == id);

        if (booking == null)
        {
            return RedirectToAction("BookIndex");
        }

         ViewBag.Customer=new SelectList(db.CustomerIvies);
        ViewBag.Source = db.FlightsIvies.Select(f => f.Source).Distinct().ToList();
        ViewBag.Destination = db.FlightsIvies.Select(f => f.Destination).Distinct().ToList();

        return View(booking);
    }

    // POST: Booking/Edit/5
    [HttpPost]
  
    public async Task<IActionResult> Edit(int id, BookingIvy booking)
    {
        if (id != booking.BookingId)
        {
            return BadRequest();
        }

        if (ModelState.IsValid)

        {

            ViewBag.Customer=new SelectList(db.CustomerIvies);
            ViewBag.Source=new SelectList(db.FlightsIvies.Select(x=>x.Source).Distinct());
            ViewBag.Destination=new SelectList(db.FlightsIvies.Select(x=>x.Destination).Distinct());
            var existingBooking=db.BookingIvies.Find(booking.BookingId);

           if(existingBooking!=null)
           {
            existingBooking.BookingDate=DateTime.Now;
            existingBooking.Source=booking.Source;
            existingBooking.Destination=booking.Destination;
            existingBooking.NoOfPassengers=booking.NoOfPassengers;
            existingBooking.CustomerId=booking.CustomerId;
            int flightId=existingBooking.FlightId??0;
            existingBooking.TotalCost=CalculateTotalCost(flightId,existingBooking.NoOfPassengers);
            // Update logic here
            //db.BookingIvies.Update(booking);
            db.Entry(existingBooking).State=EntityState.Modified;
            db.SaveChanges();
             using(var client =new HttpClient())
                {
                    StringContent content=new StringContent(JsonConvert.SerializeObject(booking),Encoding.UTF8,"application/json");
                    HttpResponseMessage response=await client.PostAsync("http://localhost:5214/api/Booking",content);

                    if(response.IsSuccessStatusCode)
                    {
                        return Ok(existingBooking); 
                    }
                else{
            return RedirectToAction("BookIndex");
            }
        
        }
        }
        return NotFound("Booking Not found");
        }

        ViewBag.Customer=new SelectList(db.CustomerIvies);
        ViewBag.Source = new SelectList(db.FlightsIvies.Select(f => f.Source).Distinct().ToList());
        ViewBag.Destination =new SelectList( db.FlightsIvies.Select(f => f.Destination).Distinct().ToList());

        return View(booking);
    }
private decimal CalculateTotalCost(int flightId,int NoOfPassengers)
{
    var flight=db.FlightsIvies.Find(flightId);
    if(flight!=null)
    {
        return flight.Rate*NoOfPassengers;
    }
    return 0;
}
    // GET: Booking/Delete/5
    public IActionResult Delete(int? id)
    {
        if (id == null)
        {
            return RedirectToAction("BookIndex");
        }

        var booking = db.BookingIvies.SingleOrDefault(b => b.BookingId == id);

        if (booking == null)
        {
            return RedirectToAction("BookIndex");
        }

        return View(booking);
    }

    // POST: Booking/Delete/5
    [HttpPost, ActionName("Delete")]
   
    public async Task<IActionResult> Delete(int id)
    {
        var booking = db.BookingIvies.SingleOrDefault(b => b.BookingId == id);

        if (booking != null)
        {
            db.BookingIvies.Remove(booking);
            db.SaveChanges();

             using(var client =new HttpClient())
                {
                    //StringContent content=new StringContent(JsonConvert.SerializeObject(booking),Encoding.UTF8,"application/json");
                    HttpResponseMessage response=await client.DeleteAsync("http://localhost:5214/api/Booking"+id);

                    if(response.IsSuccessStatusCode)
                    {
                        //return RedirectToAction("Details",new{id=booking.BookingId}); 
                        return Ok("Booking deleted successfully");
                    }
                    else{
                        return RedirectToAction("BookIndex");

                    }
                }
        }

        return RedirectToAction("BookIndex");
    }
}
}